"""
Django settings for Rasayam_website project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv

load_dotenv()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY', 'your-fallback-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    "unfold",  # <--- THIS MUST BE FIRST
    "unfold.contrib.filters",  # For better sidebar filters
    "unfold.contrib.forms",    # For modern form layouts
    "unfold.contrib.import_export",  # For that bulk upload feature we want


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "import_export",

    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rasayam_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Added this to support a global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # --- Rasayam Custom Processors ---
                'products.context_processors.cart_count', 
            ],
        },
    },
]






WSGI_APPLICATION = 'Rasayam_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (Images uploaded via Admin/Boutique Portal)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# settings.py

UNFOLD = {
    "SITE_TITLE": "RASAYAM Admin",
    "SITE_HEADER": "RASAYAM Business Portal",
    "SHOW_HISTORY": True,
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # <--- Change this to False to remove the clutter
        "navigation": [
            {
                "title": "Marketing & Storefront",
                "items": [
                    {
                        "title": "Banners",
                        "icon": "image", # Uses Google Material Symbols
                        "link": "/admin/products/banner/",
                    },
                    {
                        "title": "Promo Boxes",
                        "icon": "featured_video",
                        "link": "/admin/products/promobox/",
                    },
                ],
            },
            {
                "title": "Inventory Management",
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/products/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/products/category/",
                    },
                ],
            },
            {
                "title": "Sales & Support",
                "items": [
                    {
                        "title": "Orders",
                        "icon": "shopping_cart",
                        "link": "/admin/products/order/",
                    },
                    {
                        "title": "Customer Profiles",
                        "icon": "person",
                        "link": "/admin/products/customerprofile/",
                    },
                    {
                        "title": "Contact Inquiries",
                        "icon": "mail",
                        "link": "/admin/products/contactinquiry/",
                    },
                    {
                        "title": "Product Reviews",
                        "icon": "star",
                        "link": "/admin/products/review/",
                    },
                ],
            },
        ],
    },
}



# settings.py

# Fetching keys from the .env file you just created
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')