# Generated by Django 6.0.3 on 2026-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobox',
            options={'ordering': ['order'], 'verbose_name_plural': 'Promo Boxes'},
        ),
        migrations.AddField(
            model_name='promobox',
            name='link_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='promobox',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
