# Generated by Django 6.0.3 on 2026-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
